# Use official Node.js image as base
FROM node:latest AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy all the project files into the container
COPY . .

# Set the environment variable to run the app in production
ENV NODE_ENV=dev

# Command to run the application
CMD ["node", "app.js"]
